// Restaurant Information
export const RESTAURANT_NAME = "Califorian Restaurant";
export const RESTAURANT_TAGLINE = "Lezzetin Zirvesinde Bir Deneyim";
export const RESTAURANT_DESCRIPTION = "26 yıldır kalite ve güvenin adresi. Sağlıklı ve lezzetli yemekler ile müşterilerimizin damak zevkine en üst düzeyde hizmet sunuyoruz.";
export const RESTAURANT_PHONE = "+90 392 444 7070";

// Branches
export const BRANCHES = [
  {
    id: "lefkosa",
    name: "Lefkoşa",
    nameTr: "Lefkoşa",
    address: "Mehmet Akif Caddesi, Lefkoşa",
    addressTr: "Mehmet Akif Caddesi, Lefkoşa",
    phone: "+90 392 444 7070",
    hours: "11:00 - 23:00",
    mapUrl: "https://maps.google.com/?q=Califorian+Lefkosa",
  },
  {
    id: "gazimagusa",
    name: "Gazimağusa",
    nameTr: "Gazimağusa",
    address: "Gazimağusa",
    addressTr: "Gazimağusa",
    phone: "+90 392 365 61 70",
    hours: "11:00 - 23:00",
    mapUrl: "https://maps.google.com/?q=Califorian+Gazimagusa",
  },
  {
    id: "esentepe",
    name: "Esentepe",
    nameTr: "Esentepe",
    address: "Esentepe",
    addressTr: "Esentepe",
    phone: "+90 546 999 70 70",
    hours: "11:00 - 23:00",
    mapUrl: "https://maps.google.com/?q=Califorian+Esentepe",
  },
];

// Menu Categories
export const MENU_CATEGORIES = [
  { id: "all", name: "All", nameEn: "All", nameTr: "Tümü" },
  { id: "pizzas", name: "Pizzas", nameEn: "Pizzas", nameTr: "Pizzalar" },
  { id: "starters", name: "Starters", nameEn: "Starters", nameTr: "Başlangıçlar" },
  { id: "mains", name: "Main Courses", nameEn: "Main Courses", nameTr: "Ana Yemekler" },
  { id: "desserts", name: "Desserts", nameEn: "Desserts", nameTr: "Tatlılar" },
  { id: "beverages", name: "Beverages", nameEn: "Beverages", nameTr: "Meşrubatlar" },
  { id: "breakfast", name: "Breakfast", nameEn: "Breakfast", nameTr: "Kahvaltı" },
];

// Sample Menu Items
export const MENU_ITEMS = [
  {
    id: 1,
    name: "Bruschetta Trio",
    nameTr: "Bruschetta Üçlüsü",
    description: "Classic tomato, mushroom, and olive tapenade on toasted ciabatta",
    descriptionTr: "Kızarmış ciabatta üzerinde klasik domates, mantar ve zeytin ezmesi",
    price: 145,
    category: "starters",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600",
    tags: ["vegetarian"],
  },
  {
    id: 2,
    name: "Calamari Fritti",
    nameTr: "Kalamar Tava",
    description: "Crispy fried calamari with lemon aioli and marinara sauce",
    descriptionTr: "Limonlu aioli ve marinara sosu ile çıtır kalamar",
    price: 185,
    category: "starters",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600",
    tags: [],
  },
  {
    id: 3,
    name: "Margherita Pizza",
    nameTr: "Margherita Pizza",
    description: "San Marzano tomatoes, fresh mozzarella, basil, extra virgin olive oil",
    descriptionTr: "San Marzano domates, taze mozzarella, fesleğen, sızma zeytinyağı",
    price: 220,
    category: "pizzas",
    image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600",
    tags: ["vegetarian"],
  },
  {
    id: 4,
    name: "Quattro Formaggi",
    nameTr: "Dört Peynirli Pizza",
    description: "Mozzarella, gorgonzola, parmesan, and fontina cheese blend",
    descriptionTr: "Mozzarella, gorgonzola, parmesan ve fontina peynir karışımı",
    price: 265,
    category: "pizzas",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600",
    tags: ["vegetarian"],
  },
  {
    id: 5,
    name: "Diavola Pizza",
    nameTr: "Diavola Pizza",
    description: "Spicy salami, chili flakes, mozzarella, tomato sauce",
    descriptionTr: "Acılı salam, pul biber, mozzarella, domates sosu",
    price: 245,
    category: "pizzas",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600",
    tags: ["spicy"],
  },
  {
    id: 6,
    name: "Grilled Sea Bass",
    nameTr: "Izgara Levrek",
    description: "Mediterranean sea bass with herb butter, roasted vegetables",
    descriptionTr: "Otlu tereyağı ve kavrulmuş sebzeler ile Akdeniz levreği",
    price: 385,
    category: "mains",
    image: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600",
    tags: ["gluten-free"],
  },
  {
    id: 7,
    name: "Beef Tenderloin",
    nameTr: "Dana Bonfile",
    description: "Premium beef tenderloin with red wine reduction and truffle mash",
    descriptionTr: "Kırmızı şarap sosu ve trüflü patates püresi ile premium dana bonfile",
    price: 450,
    category: "mains",
    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=600",
    tags: [],
  },
  {
    id: 8,
    name: "Tiramisu",
    nameTr: "Tiramisu",
    description: "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone",
    descriptionTr: "Espresso emdirilmiş kadayıf ve mascarpone ile klasik İtalyan tatlısı",
    price: 95,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600",
    tags: ["vegetarian"],
  },
  {
    id: 9,
    name: "Panna Cotta",
    nameTr: "Panna Cotta",
    description: "Vanilla bean panna cotta with fresh berry compote",
    descriptionTr: "Taze meyve kompostosu ile vanilya panna cotta",
    price: 85,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600",
    tags: ["vegetarian", "gluten-free"],
  },
  {
    id: 10,
    name: "Fresh Lemonade",
    nameTr: "Taze Limonata",
    description: "House-made lemonade with fresh mint",
    descriptionTr: "Taze nane ile ev yapımı limonata",
    price: 45,
    category: "beverages",
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600",
    tags: ["vegan"],
  },
  {
    id: 11,
    name: "Espresso",
    nameTr: "Espresso",
    description: "Double shot of premium Italian espresso",
    descriptionTr: "Premium İtalyan espresso çift shot",
    price: 35,
    category: "beverages",
    image: "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=600",
    tags: ["vegan"],
  },
  {
    id: 12,
    name: "House Wine",
    nameTr: "Ev Şarabı",
    description: "Selected red or white wine by the glass",
    descriptionTr: "Seçilmiş kırmızı veya beyaz şarap (kadeh)",
    price: 75,
    category: "beverages",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600",
    tags: ["vegan"],
  },
  {
    id: 13,
    name: "Serpme Kahvaltı",
    nameTr: "Serpme Kahvaltı",
    description: "Traditional Turkish breakfast spread with cheeses, eggs, and more",
    descriptionTr: "Geleneksel Türk kahvaltısı, peynirler, yumurtalar ve daha fazlası",
    price: 250,
    category: "breakfast",
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600",
    tags: ["vegetarian"],
  },
];

// Navigation Links
export const NAV_LINKS = [
  { href: "/", labelEn: "Home", labelTr: "Ana Sayfa" },
  { href: "/menu", labelEn: "Menu", labelTr: "Menü" },
  { href: "/order", labelEn: "Order Online", labelTr: "Online Sipariş" },
  { href: "/reservations", labelEn: "Reservations", labelTr: "Rezervasyon" },
  { href: "/gallery", labelEn: "Gallery", labelTr: "Galeri" },
  { href: "/about", labelEn: "About", labelTr: "Hakkımızda" },
  { href: "/contact", labelEn: "Contact", labelTr: "İletişim" },
  { href: "/locations", labelEn: "Locations", labelTr: "Şubeler" },
];

// Testimonials
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Ayşe K.",
    text: "The best dining experience in Cyprus! The atmosphere and food are absolutely incredible.",
    textTr: "Kıbrıs'taki en iyi yemek deneyimi! Atmosfer ve yemekler kesinlikle inanılmaz.",
    rating: 5,
  },
  {
    id: 2,
    name: "Mehmet A.",
    text: "We celebrated our anniversary here. The service was impeccable and the food divine.",
    textTr: "Yıldönümümüzü burada kutladık. Servis kusursuz, yemekler muhteşemdi.",
    rating: 5,
  },
  {
    id: 3,
    name: "Sarah M.",
    text: "A hidden gem! The pizzas are authentic and the staff makes you feel like family.",
    textTr: "Gizli bir hazine! Pizzalar otantik ve personel sizi aile gibi hissettiriyor.",
    rating: 5,
  },
];

// Features
export const FEATURES = [
  {
    id: 1,
    titleEn: "Experienced & Friendly Staff",
    titleTr: "Deneyimli ve Güler Yüzlü Personel",
    descEn: "Our experienced and friendly team attentively responds to our guests' needs.",
    descTr: "Misafirlerimizin ihtiyaçlarına özenle yanıt veren deneyimli ve güler yüzlü bir ekiple hizmet veriyoruz.",
  },
  {
    id: 2,
    titleEn: "Organic & Local Ingredients",
    titleTr: "Organik ve Yerel Malzemeler",
    descEn: "We use the freshest and highest quality organic and local ingredients.",
    descTr: "En taze ve kaliteli organik ve yerel malzemeleri kullanarak lezzetlerimize özel bir tat katıyoruz.",
  },
  {
    id: 3,
    titleEn: "Breakfast Menu",
    titleTr: "Kahvaltı Menüsü",
    descEn: "Start your day with our rich breakfast options.",
    descTr: "Zengin kahvaltı seçenekleri ile güne enfes bir başlangıç yapmanızı sağlıyoruz.",
  },
  {
    id: 4,
    titleEn: "Special Events",
    titleTr: "Özel Organizasyonlar",
    descEn: "We offer spaces and services for special events and private occasions.",
    descTr: "Özel etkinlikler ve özel organizasyonlar için alanlar ve hizmetler sunuyoruz.",
  },
  {
    id: 5,
    titleEn: "Free WiFi",
    titleTr: "Ücretsiz WiFi",
    descEn: "We offer free WiFi access to make your visits more comfortable.",
    descTr: "Misafirlerimize ücretsiz Wi-Fi erişimi sunarak ziyaretlerinizi kolaylaştırıyoruz.",
  },
  {
    id: 6,
    titleEn: "Free Parking",
    titleTr: "Ücretsiz Otopark",
    descEn: "We provide free parking for our guests.",
    descTr: "Misafirlerimiz için ücretsiz otopark hizmeti sunuyoruz.",
  },
  {
    id: 7,
    titleEn: "Kid Friendly",
    titleTr: "Çocuk Dostu",
    descEn: "Family-friendly environment with kids menus and play areas.",
    descTr: "Aileler için çocuk menüleri ve oyun alanları ile aile dostu bir ortam sunuyoruz.",
  },
  {
    id: 8,
    titleEn: "VIP Rooms",
    titleTr: "Özel VIP Odalar",
    descEn: "Private VIP rooms ideal for special events and meetings.",
    descTr: "Özel VIP odalarımızda özel davetler ve özel toplantılar için ideal bir ortam sağlıyoruz.",
  },
  {
    id: 9,
    titleEn: "Outdoor Dining",
    titleTr: "Açık Hava Alanları",
    descEn: "Enjoy dining in our beautiful outdoor spaces.",
    descTr: "Açık havada yemek yeme imkanları sunan mekanlarımız bulunuyor.",
  },
  {
    id: 10,
    titleEn: "Bar Service",
    titleTr: "Bar Hizmeti",
    descEn: "Cocktails prepared by professional bartenders and a wide selection of drinks.",
    descTr: "Profesyonel barmenlerimiz tarafından hazırlanan kokteyller ve geniş içki seçenekleri.",
  },
  {
    id: 11,
    titleEn: "Catering Services",
    titleTr: "Catering Hizmetleri",
    descEn: "We provide daily meals to thousands through our catering services.",
    descTr: "Catering hizmetleriyle binlerce kişiye günlük yemek sunuyoruz.",
  },
  {
    id: 12,
    titleEn: "Special Diet Options",
    titleTr: "Özel Menü Seçenekleri",
    descEn: "Vegan, vegetarian, gluten-free and more dietary options available.",
    descTr: "Vegan, vejetaryen, glütensiz ve daha fazlası gibi özel diyet ihtiyaçlarına uygun menü seçenekleri.",
  },
];